export const movies: Movie[] = JSON.parse(
  JSON.stringify([
    {
      title: "Unspeakable Acts ",
      genre: "Horror",
      release_date: "1954-02-11T08:58:13Z",
      director: "Tera Atlee",
      actor: "Myrtia Matthesius",
      rating: 8.5,
      duration_minutes: 79,
      budget: "Yuan Renminbi",
      box_office: "Yen",
      description:
        "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    },
    {
      title: "Gator",
      genre: "Romance",
      release_date: "1904-03-08T07:26:10Z",
      director: "Clementia Jakeway",
      actor: "Juliane Megarrell",
      rating: 5.6,
      duration_minutes: 152,
      budget: "Real",
      box_office: "Peso",
      description:
        "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    },
    {
      title: "Saawariya",
      genre: "Action",
      release_date: "1982-02-02T17:17:52Z",
      director: "Inglebert Guillford",
      actor: "Padraic Rolse",
      rating: 5.9,
      duration_minutes: 227,
      budget: "Euro",
      box_office: "Dollar",
      description:
        "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    },
    {
      title: "Futurama: Bender's Game",
      genre: "Drama",
      release_date: "1924-09-11T00:06:05Z",
      director: "Emmerich Seal",
      actor: "Bay Caitlin",
      rating: 5.0,
      duration_minutes: 236,
      budget: "Yuan Renminbi",
      box_office: "Rupee",
      description:
        "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    },
    {
      title: "Nosferatu (Nosferatu, eine Symphonie des Grauens)",
      genre: "Romance",
      release_date: "1992-06-18T06:29:09Z",
      director: "Haze St. Ledger",
      actor: "Brittaney Yurin",
      rating: 3.0,
      duration_minutes: 210,
      budget: "Won",
      box_office: "Rupiah",
      description:
        "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    },
    {
      title: "Mission Congo",
      genre: "Horror",
      release_date: "1934-09-21T03:42:35Z",
      director: "Robbi Basilio",
      actor: "Libby Durden",
      rating: 8.2,
      duration_minutes: 66,
      budget: "Rupee",
      box_office: "Yuan Renminbi",
      description:
        "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    },
    {
      title: "Falling Angels",
      genre: "Horror",
      release_date: "1995-07-16T00:43:45Z",
      director: "Freddy Burdas",
      actor: "Camel Schoolfield",
      rating: 6.9,
      duration_minutes: 109,
      budget: "Euro",
      box_office: "Rupiah",
      description:
        "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    },
    {
      title: "True Legend (Su Qi-Er)",
      genre: "Romance",
      release_date: "1901-01-19T17:54:24Z",
      director: "Halsy McGoogan",
      actor: "Wendi Lawrence",
      rating: 6.7,
      duration_minutes: 103,
      budget: "Lek",
      box_office: "Peso",
      description:
        "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    },
    {
      title: "After School Special (a.k.a. Barely Legal)",
      genre: "Action",
      release_date: "1947-03-18T04:52:41Z",
      director: "Joyce Baybutt",
      actor: "Kathi Middlemiss",
      rating: 1.0,
      duration_minutes: 164,
      budget: "Ruble",
      box_office: "Real",
      description:
        "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    },
    {
      title: "Secret Agent, The",
      genre: "Horror",
      release_date: "1979-04-06T01:42:54Z",
      director: "Darell Ambrogio",
      actor: "Corinne Spaxman",
      rating: 5.2,
      duration_minutes: 155,
      budget: "Franc",
      box_office: "Peso",
      description:
        "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    },
    {
      title: "A Coming-Out Party",
      genre: "Romance",
      release_date: "1941-02-02T05:41:50Z",
      director: "Emilio Brokenshaw",
      actor: "Rachelle Scranny",
      rating: 7.9,
      duration_minutes: 116,
      budget: "Rupiah",
      box_office: "Shilling",
      description:
        "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    },
    {
      title: "Dinner for Schmucks",
      genre: "Drama",
      release_date: "1994-08-05T01:18:47Z",
      director: "Diego Barnewille",
      actor: "Corbett Sturley",
      rating: 4.9,
      duration_minutes: 111,
      budget: "Yuan Renminbi",
      box_office: "Peso",
      description:
        "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    },
    {
      title: "Indestructible Man",
      genre: "Romance",
      release_date: "1974-12-09T16:23:15Z",
      director: "Quillan Sloane",
      actor: "Barbabas Brideaux",
      rating: 0.1,
      duration_minutes: 146,
      budget: "Dollar",
      box_office: "Rupee",
      description:
        "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    },
    {
      title: "Raising Cain",
      genre: "Drama",
      release_date: "1914-11-19T02:19:37Z",
      director: "Pren Vanichkov",
      actor: "Toiboid Wolters",
      rating: 5.7,
      duration_minutes: 167,
      budget: "Naira",
      box_office: "Peso",
      description:
        "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    },
    {
      title: "Sassy Pants",
      genre: "Horror",
      release_date: "1914-07-19T16:09:33Z",
      director: "Farr Chatelet",
      actor: "Mickie Chiese",
      rating: 5.5,
      duration_minutes: 87,
      budget: "Yen",
      box_office: "Real",
      description:
        "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    },
    {
      title: "Eyes Wide Open (Einayim Petukhoth)",
      genre: "Romance",
      release_date: "1976-09-11T22:21:26Z",
      director: "Thorvald McKibbin",
      actor: "Astrid Antoniewski",
      rating: 0.7,
      duration_minutes: 84,
      budget: "Rupiah",
      box_office: "Peso",
      description:
        "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    },
    {
      title: "The Man Who Wouldn't Die",
      genre: "Comedy",
      release_date: "1992-01-22T23:21:11Z",
      director: "Nathanael Zisneros",
      actor: "Vikky Dugdale",
      rating: 7.0,
      duration_minutes: 177,
      budget: "Kuna",
      box_office: "Yuan Renminbi",
      description:
        "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    },
    {
      title: "Messenger, The",
      genre: "Drama",
      release_date: "1923-10-10T08:21:10Z",
      director: "Abbie Puckring",
      actor: "Daile Brock",
      rating: 9.2,
      duration_minutes: 119,
      budget: "Lempira",
      box_office: "Dollar",
      description:
        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    },
    {
      title: "Night Across the Street (La noche de enfrente)",
      genre: "Comedy",
      release_date: "2014-04-18T05:55:00Z",
      director: "Dorice Hughill",
      actor: "Nikaniki Gautrey",
      rating: 2.9,
      duration_minutes: 132,
      budget: "Euro",
      box_office: "Dollar",
      description:
        "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    },
    {
      title: "Fort Apache, the Bronx",
      genre: "Comedy",
      release_date: "2001-12-18T19:21:10Z",
      director: "Cazzie Donson",
      actor: "Pavel Skipworth",
      rating: 7.2,
      duration_minutes: 234,
      budget: "Yuan Renminbi",
      box_office: "Peso",
      description:
        "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    },
    {
      title: "Watcher in the Woods, The",
      genre: "Action",
      release_date: "2018-02-08T23:36:20Z",
      director: "Ella Conklin",
      actor: "Tresa Mundell",
      rating: 8.8,
      duration_minutes: 73,
      budget: "Rupee",
      box_office: "Rupiah",
      description:
        "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    },
    {
      title: "Mountaintop Motel Massacre ",
      genre: "Romance",
      release_date: "1940-04-01T05:37:32Z",
      director: "Doroteya Methuen",
      actor: "Towney Arundell",
      rating: 3.6,
      duration_minutes: 123,
      budget: "Ruble",
      box_office: "Yuan Renminbi",
      description:
        "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    },
    {
      title: "Vengeance (Fuk sau)",
      genre: "Comedy",
      release_date: "1934-06-21T15:59:16Z",
      director: "Maribelle Maltster",
      actor: "Jane Cordy",
      rating: 8.5,
      duration_minutes: 134,
      budget: "Dollar",
      box_office: "Lev",
      description:
        "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    },
    {
      title: "Steal This Film II",
      genre: "Comedy",
      release_date: "1901-11-16T10:40:42Z",
      director: "Sherrie Oattes",
      actor: "Elroy Trattles",
      rating: 2.8,
      duration_minutes: 96,
      budget: "Boliviano",
      box_office: "Rupiah",
      description:
        "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    },
    {
      title: "No Rest for the Brave (Pas de repos pour les braves)",
      genre: "Romance",
      release_date: "1947-08-31T21:15:50Z",
      director: "Jarvis Attrey",
      actor: "Mercie Paynter",
      rating: 9.1,
      duration_minutes: 174,
      budget: "Dollar",
      box_office: "Rupiah",
      description:
        "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    },
    {
      title: "Heckler",
      genre: "Drama",
      release_date: "1941-05-14T20:37:37Z",
      director: "Regan Dumberrill",
      actor: "Jedd Stirzaker",
      rating: 1.0,
      duration_minutes: 193,
      budget: "Ruble",
      box_office: "Yuan Renminbi",
      description:
        "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    },
    {
      title: "Mr. Popper's Penguins",
      genre: "Romance",
      release_date: "1913-09-22T15:06:55Z",
      director: "Carina Ridler",
      actor: "Royal Leipoldt",
      rating: 8.5,
      duration_minutes: 170,
      budget: "Hryvnia",
      box_office: "Euro",
      description:
        "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    },
    {
      title: "Involuntary (De ofrivilliga)",
      genre: "Romance",
      release_date: "1969-07-30T04:02:52Z",
      director: "Fidelity Bertolin",
      actor: "Shelton Norval",
      rating: 1.2,
      duration_minutes: 94,
      budget: "Zloty",
      box_office: "Euro",
      description:
        "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    },
    {
      title: "Follow the Fleet",
      genre: "Action",
      release_date: "2001-02-10T10:53:18Z",
      director: "Dirk Raywood",
      actor: "Nikkie Le feaver",
      rating: 0.2,
      duration_minutes: 136,
      budget: "Peso",
      box_office: "Yuan Renminbi",
      description:
        "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    },
    {
      title: "8: The Mormon Proposition",
      genre: "Romance",
      release_date: "1908-01-14T21:48:18Z",
      director: "Blondie Cudbertson",
      actor: "Edita Egiloff",
      rating: 3.7,
      duration_minutes: 67,
      budget: "Peso",
      box_office: "Rupiah",
      description:
        "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    },
    {
      title: "British Intelligence",
      genre: "Action",
      release_date: "1945-11-03T23:39:13Z",
      director: "Luz Goodchild",
      actor: "Eal Camelli",
      rating: 2.7,
      duration_minutes: 238,
      budget: "Dollar",
      box_office: "Dollar",
      description:
        "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    },
    {
      title: "Puppetmaster, The (Xi meng ren sheng)",
      genre: "Romance",
      release_date: "1917-10-26T03:07:12Z",
      director: "Hillie McAline",
      actor: "Karrah Keefe",
      rating: 9.4,
      duration_minutes: 190,
      budget: "Euro",
      box_office: "Rupiah",
      description:
        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",
    },
    {
      title: "Ice Men",
      genre: "Drama",
      release_date: "2010-11-12T00:38:38Z",
      director: "Dallas Hellwing",
      actor: "Leanor Andretti",
      rating: 7.0,
      duration_minutes: 132,
      budget: "Peso",
      box_office: "Real",
      description:
        "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    },
    {
      title: "Big Girls Don't Cry... They Get Even (Stepkids)",
      genre: "Romance",
      release_date: "2010-08-23T07:26:09Z",
      director: "Taddeo Kitcatt",
      actor: "Marice Straun",
      rating: 2.5,
      duration_minutes: 225,
      budget: "Peso",
      box_office: "Yuan Renminbi",
      description:
        "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    },
    {
      title: "Your Life in 65 (Tu vida en 65')",
      genre: "Drama",
      release_date: "1981-09-11T03:02:15Z",
      director: "Wynn Fivey",
      actor: "Dorie Donett",
      rating: 5.4,
      duration_minutes: 82,
      budget: "Rupiah",
      box_office: "Ruble",
      description:
        "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    },
    {
      title: "Angel in My Pocket",
      genre: "Horror",
      release_date: "2022-04-02T21:51:40Z",
      director: "Darbee Tibbetts",
      actor: "Bronson Josovich",
      rating: 5.1,
      duration_minutes: 129,
      budget: "Rupee",
      box_office: "Real",
      description:
        "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    },
    {
      title: "'Neath the Arizona Skies",
      genre: "Action",
      release_date: "2020-07-02T23:00:16Z",
      director: "Inness Youngman",
      actor: "Fey Drennan",
      rating: 5.6,
      duration_minutes: 125,
      budget: "Rupiah",
      box_office: "Euro",
      description:
        "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    },
    {
      title: "Papusza",
      genre: "Action",
      release_date: "1993-01-07T22:18:54Z",
      director: "Irita Bortoletti",
      actor: "Tonia Hirjak",
      rating: 7.3,
      duration_minutes: 158,
      budget: "Dollar",
      box_office: "Rupiah",
      description:
        "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    },
    {
      title: "Tyrannosaur",
      genre: "Horror",
      release_date: "1901-02-01T02:00:09Z",
      director: "Anne-marie Casini",
      actor: "Christian Mattinson",
      rating: 0.4,
      duration_minutes: 230,
      budget: "Dollar",
      box_office: "Euro",
      description:
        "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    },
    {
      title: "Leprechaun: Origins",
      genre: "Drama",
      release_date: "1942-08-19T16:42:01Z",
      director: "Kelly Trustey",
      actor: "Lowrance Martinson",
      rating: 9.6,
      duration_minutes: 134,
      budget: "Dollar",
      box_office: "Tenge",
      description:
        "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    },
    {
      title: "Ditchdigger's Daughters, The",
      genre: "Drama",
      release_date: "2011-10-27T02:47:05Z",
      director: "Waylon Gepp",
      actor: "Shara MacVanamy",
      rating: 6.6,
      duration_minutes: 195,
      budget: "Yuan Renminbi",
      box_office: "Rupiah",
      description:
        "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    },
    {
      title: "Virtuosity",
      genre: "Action",
      release_date: "1929-01-27T10:15:58Z",
      director: "Bartlett Heartfield",
      actor: "Shaw Toe",
      rating: 8.3,
      duration_minutes: 187,
      budget: "Yuan Renminbi",
      box_office: "Euro",
      description:
        "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    },
    {
      title: "Salut cousin!",
      genre: "Horror",
      release_date: "1989-09-15T20:26:45Z",
      director: "Raleigh Armin",
      actor: "Nanny Sheavills",
      rating: 8.1,
      duration_minutes: 115,
      budget: "Rial",
      box_office: "Rupiah",
      description:
        "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    },
    {
      title: "Branded to Kill (Koroshi no rakuin)",
      genre: "Horror",
      release_date: "1903-01-04T19:27:31Z",
      director: "Lindsey Treece",
      actor: "Ettore Filipic",
      rating: 5.5,
      duration_minutes: 168,
      budget: "Rupiah",
      box_office: "Zloty",
      description:
        "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    },
    {
      title: "Matinee",
      genre: "Action",
      release_date: "1979-01-23T17:47:56Z",
      director: "Keriann Deyenhardt",
      actor: "Shannan Hudghton",
      rating: 7.8,
      duration_minutes: 120,
      budget: "Zloty",
      box_office: "Rupiah",
      description:
        "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    },
    {
      title: "Alyce Kills",
      genre: "Horror",
      release_date: "1929-02-23T22:43:59Z",
      director: "Lorrie Ebdon",
      actor: "Ingar Godain",
      rating: 2.1,
      duration_minutes: 163,
      budget: "Baht",
      box_office: "Bolivar",
      description:
        "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    },
    {
      title: "Devil's Chair, The",
      genre: "Comedy",
      release_date: "2011-07-17T09:09:37Z",
      director: "Ardis Conyers",
      actor: "Dominique Piddocke",
      rating: 9.9,
      duration_minutes: 78,
      budget: "Real",
      box_office: "Zloty",
      description:
        "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    },
    {
      title: "Tekken",
      genre: "Drama",
      release_date: "1953-04-04T21:33:12Z",
      director: "Renata Haine",
      actor: "Elicia Gretton",
      rating: 2.8,
      duration_minutes: 129,
      budget: "Shekel",
      box_office: "Euro",
      description:
        "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.",
    },
    {
      title: "Three to Tango",
      genre: "Drama",
      release_date: "1941-05-28T09:22:12Z",
      director: "Janek De Ortega",
      actor: "Egan Proctor",
      rating: 2.7,
      duration_minutes: 168,
      budget: "Yen",
      box_office: "Yuan Renminbi",
      description:
        "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    },
    {
      title: "Frozen Assets",
      genre: "Action",
      release_date: "1965-04-08T20:40:36Z",
      director: "Claybourne Isakovitch",
      actor: "Paule Ible",
      rating: 8.8,
      duration_minutes: 232,
      budget: "Pound",
      box_office: "Yuan Renminbi",
      description:
        "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    },
    {
      title: "Into the Storm",
      genre: "Action",
      release_date: "1941-09-15T23:22:52Z",
      director: "Don Cordelle",
      actor: "Cathie Penhaleurack",
      rating: 5.8,
      duration_minutes: 222,
      budget: "Real",
      box_office: "Euro",
      description:
        "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    },
    {
      title: "Ferryman, The",
      genre: "Comedy",
      release_date: "1953-09-03T09:38:30Z",
      director: "Bartlet Spira",
      actor: "Diena Shalders",
      rating: 3.8,
      duration_minutes: 133,
      budget: "Hryvnia",
      box_office: "Yuan Renminbi",
      description:
        "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    },
    {
      title: "Microcosmos (Microcosmos: Le peuple de l'herbe)",
      genre: "Action",
      release_date: "2020-03-06T14:21:02Z",
      director: "Yehudi Grafhom",
      actor: "Michelina Birley",
      rating: 4.5,
      duration_minutes: 135,
      budget: "Naira",
      box_office: "Yuan Renminbi",
      description:
        "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    },
    {
      title: "Pluto's Christmas Tree",
      genre: "Horror",
      release_date: "2022-03-04T01:04:21Z",
      director: "Andra Praill",
      actor: "Kendre Hillum",
      rating: 1.4,
      duration_minutes: 71,
      budget: "Shilling",
      box_office: "Dollar",
      description:
        "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    },
    {
      title: "See You Next Tuesday",
      genre: "Horror",
      release_date: "1992-05-18T18:27:25Z",
      director: "Paolo Carwithan",
      actor: "Morissa Serrier",
      rating: 9.5,
      duration_minutes: 181,
      budget: "Guilder",
      box_office: "Ruble",
      description:
        "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    },
    {
      title: "Beautiful Darling",
      genre: "Drama",
      release_date: "1936-04-06T21:31:24Z",
      director: "Brunhilde Sealand",
      actor: "Kelcie Marshall",
      rating: 8.2,
      duration_minutes: 200,
      budget: "Yuan Renminbi",
      box_office: "Euro",
      description:
        "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    },
    {
      title: "Dunwich Horror, The",
      genre: "Horror",
      release_date: "2002-06-06T15:09:02Z",
      director: "Duane Scamel",
      actor: "Gregorio Lawlan",
      rating: 8.1,
      duration_minutes: 81,
      budget: "Ruble",
      box_office: "Yuan Renminbi",
      description: "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
    },
    {
      title: "Cameron's Closet",
      genre: "Drama",
      release_date: "1913-06-05T21:16:56Z",
      director: "Jemmy Sillars",
      actor: "Elissa MacCaull",
      rating: 2.4,
      duration_minutes: 148,
      budget: "Baht",
      box_office: "Krona",
      description:
        "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    },
    {
      title: "Great Gatsby, The",
      genre: "Comedy",
      release_date: "1942-11-04T04:44:56Z",
      director: "Falito Nelm",
      actor: "Karee Keepe",
      rating: 6.9,
      duration_minutes: 76,
      budget: "Shilling",
      box_office: "Dollar",
      description:
        "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    },
    {
      title: "Girl of Finland (Lapualaismorsian)",
      genre: "Drama",
      release_date: "1908-07-11T16:52:56Z",
      director: "Barr Lucock",
      actor: "Jyoti Shafier",
      rating: 4.5,
      duration_minutes: 219,
      budget: "Zloty",
      box_office: "Euro",
      description:
        "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    },
    {
      title: "Moral Tales, Filmic Issues",
      genre: "Comedy",
      release_date: "1956-02-22T17:08:09Z",
      director: "Dede Shallcroff",
      actor: "Hakim Basilio",
      rating: 7.0,
      duration_minutes: 205,
      budget: "Euro",
      box_office: "Somoni",
      description:
        "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    },
    {
      title: "Outlaw",
      genre: "Romance",
      release_date: "2002-11-17T02:58:20Z",
      director: "Gretel Yearby",
      actor: "Kimbra Fearenside",
      rating: 4.4,
      duration_minutes: 222,
      budget: "Rupiah",
      box_office: "Ruble",
      description:
        "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    },
    {
      title: "Major and the Minor, The",
      genre: "Horror",
      release_date: "2022-12-27T13:22:37Z",
      director: "Blondell Kryska",
      actor: "Martica Westmarland",
      rating: 6.0,
      duration_minutes: 213,
      budget: "Shekel",
      box_office: "Yuan Renminbi",
      description:
        "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    },
    {
      title: "L'instant et la patience ",
      genre: "Romance",
      release_date: "1950-12-28T11:10:43Z",
      director: "Kath Braden",
      actor: "Janela Monkeman",
      rating: 2.6,
      duration_minutes: 82,
      budget: "Yuan Renminbi",
      box_office: "Rupiah",
      description:
        "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    },
    {
      title: "Sea Hawk, The",
      genre: "Action",
      release_date: "1964-04-18T20:08:02Z",
      director: "Elvina Pritchitt",
      actor: "Jeni Castelin",
      rating: 2.8,
      duration_minutes: 146,
      budget: "Peso",
      box_office: "Rupiah",
      description:
        "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    },
    {
      title: "Death Proof",
      genre: "Action",
      release_date: "1960-03-05T12:21:49Z",
      director: "Eli Kayser",
      actor: "Ardyth Sowthcote",
      rating: 2.8,
      duration_minutes: 89,
      budget: "Franc",
      box_office: "Yuan Renminbi",
      description:
        "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    },
    {
      title: "Smiling Lieutenant, The",
      genre: "Action",
      release_date: "1904-01-28T19:31:48Z",
      director: "Richmond Mesnard",
      actor: "Rori Delwater",
      rating: 2.6,
      duration_minutes: 119,
      budget: "Dollar",
      box_office: "Rand",
      description:
        "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    },
    {
      title:
        "End of Suburbia: Oil Depletion and the Collapse of the American Dream",
      genre: "Comedy",
      release_date: "1953-03-13T16:48:21Z",
      director: "Bax Jephcote",
      actor: "Randa Keijser",
      rating: 4.0,
      duration_minutes: 87,
      budget: "Koruna",
      box_office: "Hryvnia",
      description:
        "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    },
    {
      title: "Good Woman, A",
      genre: "Romance",
      release_date: "1919-10-01T01:08:38Z",
      director: "Randee Rivelin",
      actor: "Flossi Prestie",
      rating: 8.0,
      duration_minutes: 217,
      budget: "Zloty",
      box_office: "Zloty",
      description:
        "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    },
    {
      title: "Maze, The",
      genre: "Romance",
      release_date: "1939-06-02T01:44:59Z",
      director: "Ulrike Letterick",
      actor: "Koral Mabee",
      rating: 1.9,
      duration_minutes: 89,
      budget: "Zloty",
      box_office: "Hryvnia",
      description:
        "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    },
    {
      title: "Bobby",
      genre: "Comedy",
      release_date: "1944-08-31T13:56:25Z",
      director: "Caralie Osipov",
      actor: "Marsiella Aliman",
      rating: 2.2,
      duration_minutes: 209,
      budget: "Ruble",
      box_office: "Peso",
      description:
        "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    },
    {
      title: "Red Dust",
      genre: "Romance",
      release_date: "1948-07-23T04:32:25Z",
      director: "Liv Gowlett",
      actor: "Kippie Espy",
      rating: 6.9,
      duration_minutes: 196,
      budget: "Ruble",
      box_office: "Real",
      description:
        "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.",
    },
    {
      title: "Robin and Marian",
      genre: "Action",
      release_date: "1930-08-30T10:51:00Z",
      director: "Allie Hayfield",
      actor: "Valma Labbet",
      rating: 3.2,
      duration_minutes: 136,
      budget: "Yen",
      box_office: "Peso",
      description:
        "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    },
    {
      title: "Diminished Capacity",
      genre: "Action",
      release_date: "1967-01-27T17:23:05Z",
      director: "Vladimir Sharman",
      actor: "Dodi McCuffie",
      rating: 5.3,
      duration_minutes: 174,
      budget: "Rial",
      box_office: "Ruble",
      description:
        "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    },
    {
      title: "Altered States",
      genre: "Horror",
      release_date: "1908-06-16T16:58:32Z",
      director: "Rasia Cordel",
      actor: "Thedric Meale",
      rating: 2.4,
      duration_minutes: 69,
      budget: "Dong",
      box_office: "Ruble",
      description:
        "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    },
    {
      title: "Jack Reacher",
      genre: "Drama",
      release_date: "2003-04-17T18:55:43Z",
      director: "Jodi Boorne",
      actor: "Fayina Bompass",
      rating: 8.2,
      duration_minutes: 115,
      budget: "Rupiah",
      box_office: "Yuan Renminbi",
      description:
        "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    },
    {
      title: "THX 1138",
      genre: "Drama",
      release_date: "1905-06-11T04:37:48Z",
      director: "Jeffrey Jeandet",
      actor: "Darryl Jelliman",
      rating: 0.8,
      duration_minutes: 218,
      budget: "Peso",
      box_office: "Manat",
      description:
        "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    },
    {
      title: "When Ladies Meet",
      genre: "Romance",
      release_date: "2018-09-03T16:42:36Z",
      director: "Nicolis Swayte",
      actor: "Ranna Streetfield",
      rating: 1.6,
      duration_minutes: 97,
      budget: "Yuan Renminbi",
      box_office: "Ariary",
      description:
        "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    },
    {
      title: "Joke, The (Zert)",
      genre: "Action",
      release_date: "2000-06-07T02:08:12Z",
      director: "Debera Scotland",
      actor: "Milty Jurries",
      rating: 9.4,
      duration_minutes: 65,
      budget: "Dollar",
      box_office: "Peso",
      description:
        "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    },
    {
      title: "Wedding Party, The (Die Bluthochzeit)",
      genre: "Drama",
      release_date: "1902-07-31T10:40:17Z",
      director: "Mitzi McNiven",
      actor: "Barbette Gregg",
      rating: 6.5,
      duration_minutes: 147,
      budget: "Rupiah",
      box_office: "Rupiah",
      description:
        "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    },
    {
      title: "Couples Retreat",
      genre: "Drama",
      release_date: "1909-04-08T19:14:36Z",
      director: "Terencio Scudders",
      actor: "Irv Dallmann",
      rating: 8.4,
      duration_minutes: 89,
      budget: "Peso",
      box_office: "Euro",
      description:
        "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    },
    {
      title:
        "Mad Adventures of Rabbi Jacob, the (Les Aventures de Rabbi Jacob)",
      genre: "Romance",
      release_date: "2010-09-24T11:30:00Z",
      director: "Marj Liptrod",
      actor: "Ardeen Giovanizio",
      rating: 7.6,
      duration_minutes: 110,
      budget: "Franc",
      box_office: "Rupee",
      description:
        "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    },
    {
      title: "Holiday, The",
      genre: "Drama",
      release_date: "2004-06-10T17:09:42Z",
      director: "Esma Milesap",
      actor: "Diann Daine",
      rating: 1.4,
      duration_minutes: 219,
      budget: "Afghani",
      box_office: "Euro",
      description:
        "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    },
    {
      title: "Librarian: Return to King Solomon's Mines, The",
      genre: "Drama",
      release_date: "1917-04-18T11:38:12Z",
      director: "Marie Foukx",
      actor: "Zabrina Blackboro",
      rating: 2.9,
      duration_minutes: 199,
      budget: "Peso",
      box_office: "Euro",
      description: "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
    },
    {
      title: "Christmas Carol, A (Scrooge)",
      genre: "Horror",
      release_date: "1992-06-21T14:23:12Z",
      director: "Ferdinande Heinl",
      actor: "Misti Wickenden",
      rating: 6.1,
      duration_minutes: 234,
      budget: "Yuan Renminbi",
      box_office: "Rupiah",
      description:
        "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    },
    {
      title: "2:13",
      genre: "Drama",
      release_date: "1940-03-26T08:33:53Z",
      director: "Mal Zanutti",
      actor: "Brnaba Somerfield",
      rating: 0.1,
      duration_minutes: 164,
      budget: "Rupiah",
      box_office: "Peso",
      description:
        "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    },
    {
      title: "Farsan",
      genre: "Drama",
      release_date: "1997-08-19T22:22:46Z",
      director: "Fowler Pratton",
      actor: "Karlee Barenskie",
      rating: 6.2,
      duration_minutes: 127,
      budget: "Euro",
      box_office: "Rupiah",
      description:
        "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    },
    {
      title: "Endeavour",
      genre: "Action",
      release_date: "2021-08-05T06:04:23Z",
      director: "Shanie Nilges",
      actor: "Melessa Craft",
      rating: 0.5,
      duration_minutes: 179,
      budget: "Euro",
      box_office: "Peso",
      description: "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
    },
    {
      title: "Belarmino",
      genre: "Horror",
      release_date: "1966-03-22T02:45:46Z",
      director: "Windy Khristyukhin",
      actor: "Stephani Conduit",
      rating: 4.5,
      duration_minutes: 183,
      budget: "Euro",
      box_office: "Shilling",
      description:
        "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    },
    {
      title:
        "Nightmare Castle (Amanti d'oltretomba) (Lovers from Beyond the Tomb) (Faceless Monster, The)",
      genre: "Action",
      release_date: "1944-07-06T21:04:11Z",
      director: "Shep Harkes",
      actor: "Eada Pennicott",
      rating: 1.7,
      duration_minutes: 94,
      budget: "Peso",
      box_office: "Euro",
      description:
        "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    },
    {
      title: "Joysticks",
      genre: "Action",
      release_date: "1928-12-20T11:33:28Z",
      director: "Burlie Enders",
      actor: "Nathaniel O'Bradden",
      rating: 6.6,
      duration_minutes: 60,
      budget: "Rupiah",
      box_office: "Rupiah",
      description:
        "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    },
    {
      title: "December 7th",
      genre: "Drama",
      release_date: "1954-01-06T08:44:52Z",
      director: "Gib Eppson",
      actor: "Luce Ibbetson",
      rating: 7.8,
      duration_minutes: 153,
      budget: "Rupiah",
      box_office: "Real",
      description:
        "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    },
    {
      title: "Reds",
      genre: "Drama",
      release_date: "2003-08-10T02:48:14Z",
      director: "Emma Russilll",
      actor: "Adelaide Philps",
      rating: 6.9,
      duration_minutes: 77,
      budget: "Euro",
      box_office: "Peso",
      description:
        "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    },
    {
      title: "Don Quixote",
      genre: "Romance",
      release_date: "1974-12-19T09:40:02Z",
      director: "Clint Dimsdale",
      actor: "Candida MacKilroe",
      rating: 5.5,
      duration_minutes: 200,
      budget: "Kuna",
      box_office: "Krona",
      description:
        "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    },
    {
      title: "Ride the High Country",
      genre: "Horror",
      release_date: "1990-06-23T05:34:49Z",
      director: "Bonnie Bromont",
      actor: "Geraldine Costall",
      rating: 4.0,
      duration_minutes: 179,
      budget: "Yuan Renminbi",
      box_office: "Dollar",
      description:
        "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    },
    {
      title: "Aliens",
      genre: "Drama",
      release_date: "1941-06-12T01:55:29Z",
      director: "Johann Sends",
      actor: "Cherri Wason",
      rating: 8.7,
      duration_minutes: 66,
      budget: "Peso",
      box_office: "Yuan Renminbi",
      description:
        "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    },
    {
      title: "Glee: The 3D Concert Movie",
      genre: "Action",
      release_date: "1909-09-24T20:08:05Z",
      director: "Nert Danneil",
      actor: "Ceil Philippon",
      rating: 6.6,
      duration_minutes: 97,
      budget: "Rupiah",
      box_office: "Peso",
      description:
        "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    },
    {
      title: "Dr. Terror's House of Horrors",
      genre: "Action",
      release_date: "2002-11-23T11:42:14Z",
      director: "Fionna Castangia",
      actor: "Kurt Andreasson",
      rating: 2.0,
      duration_minutes: 69,
      budget: "Krona",
      box_office: "Yuan Renminbi",
      description:
        "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    },
    {
      title: "Three (a.k.a. 3 Extremes II) (Saam gaang)",
      genre: "Comedy",
      release_date: "1921-11-13T01:33:42Z",
      director: "Maible Lepper",
      actor: "Fax Brumfield",
      rating: 4.3,
      duration_minutes: 112,
      budget: "Naira",
      box_office: "Dram",
      description:
        "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    },
    {
      title: "Gate of Hell (Jigokumon)",
      genre: "Comedy",
      release_date: "1964-08-13T22:33:07Z",
      director: "West Scardifield",
      actor: "Ambros Bazoge",
      rating: 6.0,
      duration_minutes: 132,
      budget: "Yuan Renminbi",
      box_office: "Real",
      description:
        "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    },
  ]),
  dateReviver
);

export type Movie = {
  title: string,
  genre: string,
  release_date: Date,
  director: string,
  actor: string,
  rating: number,
  duration_minutes: number,
  budget: string,
  box_office: string,
  description: string
}

function dateReviver(key, value) {
  // Check if the value is a string and matches ISO 8601 date formats
  if (typeof value === "string") {
    const isoDatePattern = /^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(.\d{3})?Z)?$/;

    if (isoDatePattern.test(value)) {
      return new Date(value);
    }
  }
  return value;
}
